name: Publish the library

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: NPM install, lint, build, test
        run: |
          npm ci
          npm run lint -- ngx-reactive-loading
          npm run build:lib
          npm run test:lib:headless

      - name: Apply codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/ngx-reactive-loading/lcov.info

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release --debug
