name: Publish the library

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: NPM install, lint, build, test and release
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run lint -- ngx-reactive-loading
          npm run build
          npm run test:lib:headless 
          npm run build:lib
          npx semantic-release --debug

      - name: Codecov
        uses: codecov/codecov-action@v2
