name: Publish the library

on:
  push:
    branches:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: NPM install, lint, build, test
        run: |
          yarn install --frozen-lockfile
          npm run lint -- ngx-reactive-loading
          npm run build:lib
          npm run test:lib:headless

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/ngx-reactive-loading/lcov.info

      - name: Release
        run: |
          npx semantic-release --debug
